// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import "time"

// Time is an autogenerated mock type for the Time type
type Time struct {
	mock.Mock
}

// Now provides a mock function with given fields:
func (_m *Time) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// Parse provides a mock function with given fields: layout, value
func (_m *Time) Parse(layout string, value string) (time.Time, error) {
	ret := _m.Called(layout, value)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(string, string) time.Time); ok {
		r0 = rf(layout, value)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(layout, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Since provides a mock function with given fields: t
func (_m *Time) Since(t time.Time) time.Duration {
	ret := _m.Called(t)

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(time.Time) time.Duration); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}
